services:
#  mongodbatlas:
#    image: 'mongodb/mongodb-atlas-local:latest'
#    ports:
#      - '27017'
  mysql:
    image: 'mysql:8.4.3'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - ${MYSQL_PORT}
#  ollama:
#    image: 'ollama/ollama:latest'
#    ports:
#      - '11434'
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
